# Generated by Django 2.0.7 on 2018-07-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='Телефон'),
        ),
    ]
